import { IsNotEmpty } from "class-validator";
import { BookingEvent } from "../interface/booking-event.interface";



export class CreateBookingDto {
    @IsNotEmpty()
    date: string;     // day - month - year
    @IsNotEmpty()
    branch: string;     // branchId
    
    invoiceNumber: string;  // GS
    @IsNotEmpty()
    carOwner: string;
    
    technicians: string[];
    @IsNotEmpty()
    car: string;

    driver: string;  // GS
    events: BookingEvent[] // GS 
}

// * GS  : Generated by System