import { IsNotEmpty } from "class-validator";
import { BookingEvent } from "../interface/booking-event.interface";
import { IsBookingDate } from "../../helper/pipe-helper";



export class CreateBookingDto {
    @IsNotEmpty()
    @IsBookingDate({
        message: 'Date must be in format DD-MM-YYYY or DD/MM/YYYY'
    })
    date: string;     // day - month - year
    @IsNotEmpty()
    branch: string;     // branchId    
    @IsNotEmpty()
    carOwner: string;    
    @IsNotEmpty()
    carNumberPlate: string;        
}

// * GS  : Generated by System
// {
// 	   "date": "04-05-2020", 
//     "branch": "5eb0268d16fe78113ff04298", 
//     "carOwner": "5eb0268b16fe78113ff04296", 
//     "driver": "5eb0268b16fe78113ff04296",  
//     "car": "5eb0268d16fe78113ff04297", 
//     "events": [
     
//     ]
// }