// * ABC = ASSIGNED BY CUSTOMER
// * ABD = ASSIGNED BY DRIVER
// * ABT = ASSIGNED BY TECHNICIAN

export enum BookingEventsEnum {

    ORDERED,  // ABC
    DRIVER_REQUEST_SERVICE,  // ABD
    CUSTOMER_ASSIGNED_DRIVER,  // ABC
    CAR_PICKING_TIME,  // ABC
    DRIVER_PICKED_CAR, // ABD
    TECHNICIAN_RECEIVE_THE_CAR,  // ABT
    START_SERVICE,      // ABT
    FINISH_SERVICE,     // ABT
    DRIVER_DELIVERED_CAR, // ABD
    CUSTOMER_RECEIVED_CAR // ABC

}


