export enum BookingEvents {

    ORDERED,
    ASSIGNED_DRIVER,
    CAR_PICKING_TIME,
    DRIVER_PICKED_CAR,
    TECHNICIAN_RECEIVE_THE_CAR,
    START_SERVICE,
    FINISH_SERVICE,
    DRIVER_DELIVERED_CAR,
    CAR_OWNER_RECEIVED_CAR

}