// * ABC = ASSIGNED BY CUSTOMER
// * ABD = ASSIGNED BY DRIVER
// * ABT = ASSIGNED BY TECHNICIAN

export enum BookingEventsEnum {

    ORDERED = "ORDERED",  // ABC
    DRIVER_REQUEST_SERVICE = "DRIVER_REQUEST_SERVICE",  // ABD
    CUSTOMER_ASSIGNED_DRIVER = "CUSTOMER_ASSIGNED_DRIVER",  // ABC
    CAR_PICKING_TIME = "CAR_PICKING_TIME",  // ABC
    DRIVER_PICKED_CAR = "DRIVER_PICKED_CAR", // ABD
    TECHNICIAN_RECEIVE_THE_CAR = "TECHNICIAN_RECEIVE_THE_CAR",  // ABT
    START_SERVICE = "START_SERVICE",      // ABT
    FINISH_SERVICE = "FINISH_SERVICE",     // ABT
    DRIVER_DELIVERED_CAR = "DRIVER_DELIVERED_CAR", // ABD
    CUSTOMER_RECEIVED_CAR = "CUSTOMER_RECEIVED_CAR", // ABC

}


